package com.example.nplus1.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "`user`") // escape reserved keyword
@Getter
@NamedEntityGraph(
        name = "group_with_all_associations",
        attributeNodes = {
                @NamedAttributeNode(value = "orders", subgraph = "order_all")
        },
        subgraphs = {
                @NamedSubgraph(name = "order_all", attributeNodes = @NamedAttributeNode("orderDetails"))
        }
)
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String email;

    // without mappedBy
    // @OneToMany
    // Hibernate: create table "order" (id bigint generated by default as identity, time timestamp, total_price integer not null, "user_id" bigint, primary key (id))
    // Hibernate: create table "user" (id bigint generated by default as identity, email varchar(255), name varchar(255), primary key (id))
    // Hibernate: create table "user_orders" ("user_id" bigint not null, "orders_id" bigint not null)
    @OneToMany(mappedBy = "user", fetch = FetchType.EAGER)
    @Fetch(FetchMode.JOIN)
    private Set<Order> orders;

    protected User() {
    }

    public User(String name, String email) {
        this.name = name;
        this.email = email;
    }

//    public void addOrder(Order order){
//        this.orders.add(order);
//    }
}
