package com.example.nplus1.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "`user`") // escape reserved keyword
@Getter
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String email;

    // without mappedBy
    // @OneToMany
    // Hibernate: create table "order" (id bigint generated by default as identity, time timestamp, total_price integer not null, "user_id" bigint, primary key (id))
    // Hibernate: create table "user" (id bigint generated by default as identity, email varchar(255), name varchar(255), primary key (id))
    // Hibernate: create table "user_orders" ("user_id" bigint not null, "orders_id" bigint not null)
    @OneToMany(mappedBy = "user")
    private List<Order> orders = new ArrayList<>();

    protected User() {
    }

    public User(String name, String email) {
        this.name = name;
        this.email = email;
    }

//    public void addOrder(Order order){
//        this.orders.add(order);
//    }
}
