create table item
(
    id    bigint generated by default as identity,
    name  varchar(255),
    price integer not null,
    primary key (id)
);

create table "order"
(
    id          bigint generated by default as identity,
    time        timestamp,
    total_price integer not null,
    "user_id"   bigint,
    primary key (id)
);

create table order_detail
(
    id         bigint generated by default as identity,
    price      integer not null,
    quantity   integer not null,
    item_id    bigint,
    "order_id" bigint,
    primary key (id)
);

create table "user"
(
    id    bigint generated by default as identity,
    email varchar(255),
    name  varchar(255),
    primary key (id)
);

alter table "order"
    add constraint FK5ds52cnxjw9c99ovccne0axk0 foreign key ("user_id") references "user";

alter table order_detail
    add constraint FK4dtqbi7ilse9x730y087wagm2 foreign key (item_id) references item;

alter table order_detail
    add constraint FK68mf7v62attypi34kgadriu28 foreign key ("order_id") references "order";
